spring.application.name=graphqlclient

# This client application exposes its own GraphQL endpoint (a gateway)
spring.graphql.path=/graphql
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.schema.introspection.enabled=true

# Run on a different port than the backend (8080)
server.port=8081

# URL of the backend springboot-graphql-app GraphQL endpoint to connect to
backend.graphql.url=http://localhost:8080/graphql
